### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by daolvcntt** [qnts/jwt_provider#3]
Please help me. When submit login
[](url)
Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi

execute(self.server.app)

File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute

application_iter = app(environ, start_response)

File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 440, in app

return self.app(e, s)

File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 124, in application

return application_unproxied(environ, start_response)

File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 99, in application_unproxied

result = odoo.http.root(environ, start_response)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 1295, in __call__

return self.dispatch(environ, start_response)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 1263, in __call__

return self.app(environ, start_wrapped)

File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__

return self.app(environ, start_response)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 1465, in dispatch

result = ir_http._dispatch()

File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch

return super(Http, cls)._dispatch()

File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch

return super(IrHttp, cls)._dispatch()

File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch

response = super(IrHttp, cls)._dispatch()

File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 512, in _dispatch

result = super(IrHttp, cls)._dispatch()

File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 241, in _dispatch

return cls._handle_exception(e)

File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception

response = super(IrHttp, cls)._handle_exception(exc)

File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 602, in _handle_exception

return super(IrHttp, cls)._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception

return request._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 744, in _handle_exception

return super(HttpRequest, self)._handle_exception(exception)

File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception

raise exception.with_traceback(None) from new_cause

TypeError: _login() got an unexpected keyword argument 'user_agent_env' - - -

**Comment by qnts** [comment]
Hi @daolvcntt,

I saw that you already fixed your problem regarding the login in odoo 14. This module however is not tested in that version. If nothing happens I'll close the ticket.

Regards,

**Comment by Boca13** [comment]
Hello @daolvcntt,

Could you share what you did to get this great module working with Odoo 14? I gather that the problem is that the signature for the method _login changed adding the user agent environment: _login(db, login, password, user_agent_env)

However, the changes that I've tried didn't make it work. Could you give me a hint or share your code?

Thank you

**Comment by daolvcntt** [comment]
Hi @Boca13 
U can clone it here: [#link](https://github.com/daolvcntt/jwt_provider_odoo.git). I change to make it work on v14.

**Comment by Boca13** [comment]
Thank you, @daolvcntt. I tried it and I get similar errors with both normal login and the jwt login endpoint. I'll leave them here in case you have any ideas. Otherwise, thank you anyway for your help.

**POST /api/login**
```
2021-01-19 09:37:46,974 16 ERROR libnamic21 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1295, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1263, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1465, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 181, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 512, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 602, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 744, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _login() got an unexpected keyword argument 'user_agent_env' - - -
```

**(Odoo normal user login) POST /web/login**
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/controllers/main.py", line 112, in web_login
    return super().web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 921, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1002, in authenticate
    uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/res_users.py", line 76, in authenticate
    uid = super(ResUsers, cls).authenticate(db, login, password, user_agent_env)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 713, in authenticate
    uid = cls._login(db, login, password, user_agent_env=user_agent_env)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 806, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/controllers/main.py", line 112, in web_login
    return super().web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/controllers/main.py", line 21, in web_login
    response = super(AuthSignupHome, self).web_login(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 921, in web_login
    uid = request.session.authenticate(request.session.db, request.params['login'], request.params['password'])
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1002, in authenticate
    uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/res_users.py", line 76, in authenticate
    uid = super(ResUsers, cls).authenticate(db, login, password, user_agent_env)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 713, in authenticate
    uid = cls._login(db, login, password, user_agent_env=user_agent_env)
TypeError: _login() got an unexpected keyword argument 'user_agent_env'
```

**Comment by daolvcntt** [comment]
@Boca13 Have you tried the link I sent yet?

**Comment by Boca13** [comment]
> @Boca13 Have you tried the link I sent yet?

@daolvcntt Yes, my error stack was just like yours when I tried the original module for v13. The last errors are from trying with the version from your repo.

Thank you very much anyway
